workflows:
  ios-method-2:
    name: iOS signing method-2 workflow
    max_build_duration: 60
    environment:
      ios_signing:
        provisioning_profiles:
          - kanishkaa_appstore_profile
        certificates:
          - Distribute_Certificate

    # ⬇️ LINK YOUR UI INTEGRATION AT THE WORKFLOW ROOT LEVEL ⬇️
    integrations:
      app_store_connect: 'Kanishkaa attendance app'

    scripts:
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration  # 💡 Tells Codemagic to look at the 'integrations' block above
        submit_to_testflight: true
      email:
        recipients:
          - tallysriram007@gmail.com