workflows:
  ios-method-2:
    name: iOS signing method-2 workflow
    max_build_duration: 60
    environment:
      ios_signing:
        provisioning_profiles:
          - Kanishkaa Mobile Distribution
        certificates:
          - Kanishkaa Attendance Distribution

    # integrations:
    #   app_store_connect: 'Kanishkaa attendance app'

    scripts:
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key_id: $APP_STORE_CONNECT_KEY_ID
        key_id: 67BGU4Y9H5
        issuer_id: 7f630180-39c4-4d47-be0a-d6b37961beb6
        # auth: integration  # 💡 Tells Codemagic to look at the 'integrations' block above
        submit_to_testflight: true
        beta_groups:
          - kanishkaa_group
      email:
        recipients:
          - appletabperumal@icloud.com