workflows:
  ios-release:
    name: iOS Release

    environment:
      flutter: stable
      xcode: latest
      groups:
        - kanishka_env

    integrations:
      app_store_connect: Kanishkaa attendance app

    scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager

      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - tallysriram007@gmail.com