// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTOs1vyzRSBo9xvath4-K7U6x6NSA8ZM',
    appId: '1:849694091680:web:9ddc4a41725275e8555cc5',
    messagingSenderId: '849694091680',
    projectId: 'attendance-management-6e64a',
    authDomain: 'attendance-management-6e64a.firebaseapp.com',
    storageBucket: 'attendance-management-6e64a.firebasestorage.app',
    measurementId: 'G-2RW8XBYXQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3HBcE8CAloVaUmj2N_tdgy-7WfUkw_o',
    appId: '1:849694091680:android:117ec872e8554644555cc5',
    messagingSenderId: '849694091680',
    projectId: 'attendance-management-6e64a',
    storageBucket: 'attendance-management-6e64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPNXIfAnYeOnTM7R6uXQIndr0knOhQSc',
    appId: '1:849694091680:ios:fc631bf6dc61dcb2555cc5',
    messagingSenderId: '849694091680',
    projectId: 'attendance-management-6e64a',
    storageBucket: 'attendance-management-6e64a.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPNXIfAnYeOnTM7R6uXQIndr0knOhQSc',
    appId: '1:849694091680:ios:fc631bf6dc61dcb2555cc5',
    messagingSenderId: '849694091680',
    projectId: 'attendance-management-6e64a',
    storageBucket: 'attendance-management-6e64a.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTOs1vyzRSBo9xvath4-K7U6x6NSA8ZM',
    appId: '1:849694091680:web:e77c576cbd20d78c555cc5',
    messagingSenderId: '849694091680',
    projectId: 'attendance-management-6e64a',
    authDomain: 'attendance-management-6e64a.firebaseapp.com',
    storageBucket: 'attendance-management-6e64a.firebasestorage.app',
    measurementId: 'G-P0HSZHXNXP',
  );
}
